### ISSUE TITLE
Flaky servlet test causing sporadic build failures

### ISSUE THREAD

**Issue by johnbley** [open-telemetry/opentelemetry-auto-instr-java#226]
When I submitted https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/225 I saw that the jdk13 test failed.  Looking through the test logs it appears it was due to 
```
Exception in thread "http-nio-38139-exec-1" java.lang.IllegalStateException: Attempted arrival of unregistered party for java.util.concurrent.Phaser@3a132f23[phase = 0 parties = 2 arrived = 2]
	at java.base/java.util.concurrent.Phaser.doArrive(Phaser.java:383)
	at java.base/java.util.concurrent.Phaser.arriveAndDeregister(Phaser.java:644)
	at java_util_concurrent_Phaser$arriveAndDeregister$1.call(Unknown Source)
	at TestServlet3$Async$_service_closure1.doCall(TestServlet3.groovy:102)
	at TestServlet3$Async$_service_closure1.doCall(TestServlet3.groovy)
```

Looking deeper I think that the logic in TestServlet3.groovy (Aysnc) is the cause here; my hypothesis is that the async work races the service() code, and arrives twice before the service code arrives even once.   I am unable to get this to reproduce for myself with ~10 tries, but when I adjust things so that the async piece looks like

```diff
       def context = req.startAsync()
       context.start {
         try {
-          phaser.arrive()
+          phaser.arriveAndAwaitAdvance()
           HttpServerTest.controller(endpoint) {
             resp.contentType = "text/plain"
             switch (endpoint) {
```

everything still passes.  Hopefully, this should properly keep the service and the async context in sync across two phases (initialize and finish) and fix this flaky test.

**Comment by trask** [comment]
Thanks, I just hit re-run on those failures (which I have to do fairly often 😄). Any help improving flaky tests is greatly appreciated.
