### ISSUE TITLE
Sporadic test failure (2x): Elasticsearch*NodeClientTest

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#438]
```
BindHttpException[Failed to bind to [39705]]; nested: ChannelException[Failed to bind to: /127.0.0.1:39705]; nested: BindException[Address already in use];
	at org.elasticsearch.http.netty3.Netty3HttpServerTransport.bindAddress(Netty3HttpServerTransport.java:430)
	at org.elasticsearch.http.netty3.Netty3HttpServerTransport.createBoundHttpAddress(Netty3HttpServerTransport.java:336)
	at org.elasticsearch.http.netty3.Netty3HttpServerTransport.doStart(Netty3HttpServerTransport.java:316)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.http.HttpServer.doStart(HttpServer.java:77)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.node.Node.start(Node.java:576)
	at Elasticsearch5NodeClientTest.setupSpec(Elasticsearch5NodeClientTest.groovy:66)
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /127.0.0.1:39705
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at org.elasticsearch.http.netty3.Netty3HttpServerTransport.lambda$bindAddress$3(Netty3HttpServerTransport.java:419)
	at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:62)
	at org.elasticsearch.http.netty3.Netty3HttpServerTransport.bindAddress(Netty3HttpServerTransport.java:416)
	... 7 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-auto-instr-java/1107/workflows/294dea03-d674-48b6-afa3-cd3f0aaf951b/jobs/9242/tests

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-auto-instr-java/1129/workflows/f7fb54e3-429b-435e-8009-45601549743f/jobs/9403/tests

**Comment by trask** [comment]
(hopefully) closed by #444
