### ISSUE TITLE
I can't run tests in the IntelliJ debugger after rebase from #77

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#79]
I get this error message when trying to use the IntelliJ debugger to run test cases:

```
Exception in thread "main" org.spockframework.util.InternalSpockError: Failed to instantiate spec 'TwilioClientTest'
	at org.spockframework.runtime.BaseSpecRunner.createSpecInstance(BaseSpecRunner.java:110)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:62)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at io.opentelemetry.auto.test.SpockRunner.run(SpockRunner.java:139)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of <bootloader>) previously initiated loading for a different type with name "io/opentelemetry/auto/instrumentation/api/AgentTracer$TracerAPI"
	at io.opentelemetry.auto.instrumentation.api.AgentTracer.<clinit>(AgentTracer.java:48)
	at io.opentelemetry.auto.test.AgentTestRunner.<clinit>(AgentTestRunner.java:85)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.spockframework.runtime.BaseSpecRunner.createSpecInstance(BaseSpecRunner.java:104)
	... 8 more
```

This seems to be consistent across all test cases.

**Comment by trask** [comment]
This is still working for me. Are you building/running the tests inside of Intellij via Gradle? e.g.

![image](https://user-images.githubusercontent.com/218610/72949135-40a35700-3d3c-11ea-9eb7-c25ba310ebfb.png)

**Comment by prydin** [comment]
That was the problem! Thank you. I wonder why it worked before...
