### ISSUE TITLE
Replacing legacy startSpan and activateSpan in tests doesn't always work

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#80]
In some test cases, root spans are manually generated by calling ```activateSpan(startSpan("test"), true)```. We have been trying to replace that with the following sequence of statements:

```
def span = TEST_TRACER.spanBuilder("test").startSpan()
def scope = TEST_TRACER.withSpan(span)
```

This yields the following error:

```
assertTraces(1) { trace(0, 3) { span(0) { operationName "test" errored false parent() tags { } } span(1) { operationName "twilio.sdk" errored false tags { "$MoreTags.SERVICE_NAME" "twilio-sdk" "$MoreTags.RESOURCE_NAME" "api.v2010.account.MessageCreator.createAsync" "$MoreTags.SPAN_TYPE" SpanTypes.HTTP_CLIENT "$Tags.COMPONENT" "twilio-sdk" "$Tags.SPAN_KIND" Tags.SPAN_KIND_CLIENT "twilio.type" "com.twilio.rest.api.v2010.account.Message" "twilio.account" "AC14984e09e497506cf0d5eb59b1f6ace7" "twilio.sid" "MMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" "twilio.status" "sent" } } span(2) { operationName "twilio.sdk" errored false tags { "$MoreTags.SERVICE_NAME" "twilio-sdk" "$MoreTags.RESOURCE_NAME" "api.v2010.account.MessageCreator.create" "$MoreTags.SPAN_TYPE" SpanTypes.HTTP_CLIENT "$Tags.COMPONENT" "twilio-sdk" "$Tags.SPAN_KIND" Tags.SPAN_KIND_CLIENT "twilio.type" "com.twilio.rest.api.v2010.account.Message" "twilio.account" "AC14984e09e497506cf0d5eb59b1f6ace7" "twilio.sid" "MMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" "twilio.status" "sent" } } } }
    |
    groovy.lang.MissingMethodException: No signature of method: io.opentelemetry.sdk.trace.RecordEventsReadableSpan.call() is applicable for argument types: (Integer, test.TwilioClientTest$__spock_feature_2_7_closure13$_closure60$_closure61) values: [0, test.TwilioClientTest$__spock_feature_2_7_closure13$_closure60$_closure61@74e47365]
    Possible solutions: wait(), any(), end(), collect(), grep(), find()
        at test.TwilioClientTest.$spock_feature_2_7_closure13$_closure60(TwilioClientTest.groovy:679)
        at test.TwilioClientTest.asynchronous call(TwilioClientTest.groovy:677)

        Caused by:
        groovy.lang.MissingMethodException: No signature of method: io.opentelemetry.sdk.trace.RecordEventsReadableSpan.call() is applicable for argument types: (Integer, test.TwilioClientTest$__spock_feature_2_7_closure13$_closure60$_closure61) values: [0, test.TwilioClientTest$__spock_feature_2_7_closure13$_closure60$_closure61@74e47365]
        Possible solutions: wait(), any(), end(), collect(), grep(), find()
            at test.TwilioClientTest.$spock_feature_2_7_closure13$_closure60(TwilioClientTest.groovy:679)
```

**Comment by trask** [comment]
The error message is confusing, but it looks like `span` is a Span.Builder, try
```
def span = TEST_TRACER.spanBuilder("test").startSpan()
```

**Comment by prydin** [comment]
Sorry. That was a typo in the bug report. The actual code does what you're suggesting. I think it's expecting the legacy AgentSpan and AgentScope types somewhere internally. I'm leaving the legacy code in the tests for now since it works. I'll take a stab at this once I've finished the refactoring of the instrumenters. I think there's something fishy in the lower levels of the test harness code.

**Comment by trask** [comment]
Oh! I know this problem! (it's happened to me but i've already forgotten about it 😭)

You can't name the variable `span` because that conflicts with the `span()` function that is called below.

**Comment by prydin** [comment]
I think you mentioned that the other day and I too forgot about it! :)
